### ISSUE TITLE
The code parsed as a innerText of a node at the end of the page.

### ISSUE THREAD

**Issue by arsahindev** [learn-co-curriculum/react-hooks-reconciliation#1]
"<p class='util--hide'>View <a href='https://learn.co/lessons/javascript-virtual-dom'&gt;VirtualLinks to an external site. DOM</a> on Learn.co and start learning to code for free.</p>" is the content being displayed at this lesson's(https://my.learn.co/courses/145/pages/reconciliation-in-react?module_item_id=17688) end.

**Comment by ihollander** [comment]
This issue appears to be related to content on Canvas rather than in GitHub. Please contact your instructors or someone in the Canvas administration for more assistance resolving this issue. Thanks!
